apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: kube-assist
    app.kubernetes.io/managed-by: kustomize
  name: notification-secret-reader-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: notification-secret-reader-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
