{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-assist.fullname" . }}-grafana-dashboard
  namespace: {{ .Values.grafana.namespace | default .Release.Namespace }}
  labels:
    {{- include "kube-assist.labels" . | nindent 4 }}
    {{ .Values.grafana.sidecar.label }}: "1"
    {{- with .Values.grafana.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.grafana.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  kube-assist-overview.json: |-
    {{- .Files.Get "dashboards/kube-assist-overview.json" | nindent 4 }}
{{- end }}
